name: Release
on: [workflow_dispatch] # Manual trigger

permissions:
  contents: write

jobs:
  build:
    environment: publish
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/openjdk/jdk:17-ubuntu
      options: --user root
    steps:
      - uses: actions/checkout@v4

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - run: ./gradlew build publishMods
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}